import type { RoleName } from '@/lib/types/database';

// Permission constants
export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: 'view_dashboard',
  VIEW_ALL_DASHBOARD: 'view_all_dashboard',

  // Workforce
  VIEW_WORKFORCE: 'view_workforce',
  MANAGE_WORKFORCE: 'manage_workforce',

  // Training
  VIEW_TRAINING: 'view_training',
  MANAGE_TRAINING: 'manage_training',

  // Field Visits
  VIEW_VISITS: 'view_visits',
  CREATE_VISIT: 'create_visit',
  MANAGE_VISITS: 'manage_visits',

  // Inspections
  VIEW_INSPECTIONS: 'view_inspections',
  CREATE_INSPECTION: 'create_inspection',
  MANAGE_INSPECTION_TEMPLATES: 'manage_inspection_templates',

  // Observations
  VIEW_OBSERVATIONS: 'view_observations',
  CREATE_OBSERVATION: 'create_observation',

  // Corrective Actions
  VIEW_ACTIONS: 'view_actions',
  CREATE_ACTION: 'create_action',
  ASSIGN_ACTION: 'assign_action',
  UPDATE_ACTION: 'update_action',
  VERIFY_ACTION: 'verify_action',
  CLOSE_ACTION: 'close_action',
  REOPEN_ACTION: 'reopen_action',

  // Vehicles
  VIEW_VEHICLES: 'view_vehicles',
  MANAGE_VEHICLES: 'manage_vehicles',

  // Reports
  VIEW_REPORTS: 'view_reports',
  EXPORT_REPORTS: 'export_reports',

  // Admin
  MANAGE_ORGANIZATION: 'manage_organization',
  MANAGE_LOCATIONS: 'manage_locations',
  MANAGE_ROLES: 'manage_roles',
  MANAGE_USERS: 'manage_users',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  MANAGE_BRANDING: 'manage_branding',
  MANAGE_CONTRACTORS: 'manage_contractors',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Role-Permission mapping
export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  CLIENT_ADMIN: Object.values(PERMISSIONS),
  REGIONAL_MANAGER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALL_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.MANAGE_WORKFORCE,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.MANAGE_TRAINING,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.CREATE_VISIT,
    PERMISSIONS.MANAGE_VISITS,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.CREATE_INSPECTION,
    PERMISSIONS.VIEW_OBSERVATIONS,
    PERMISSIONS.CREATE_OBSERVATION,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.CREATE_ACTION,
    PERMISSIONS.ASSIGN_ACTION,
    PERMISSIONS.UPDATE_ACTION,
    PERMISSIONS.VERIFY_ACTION,
    PERMISSIONS.CLOSE_ACTION,
    PERMISSIONS.REOPEN_ACTION,
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.MANAGE_VEHICLES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.MANAGE_LOCATIONS,
  ],
  AREA_MANAGER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALL_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.MANAGE_WORKFORCE,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.MANAGE_TRAINING,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.CREATE_VISIT,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.CREATE_INSPECTION,
    PERMISSIONS.VIEW_OBSERVATIONS,
    PERMISSIONS.CREATE_OBSERVATION,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.CREATE_ACTION,
    PERMISSIONS.ASSIGN_ACTION,
    PERMISSIONS.UPDATE_ACTION,
    PERMISSIONS.VERIFY_ACTION,
    PERMISSIONS.CLOSE_ACTION,
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  FIELD_OFFICER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.CREATE_VISIT,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.CREATE_INSPECTION,
    PERMISSIONS.VIEW_OBSERVATIONS,
    PERMISSIONS.CREATE_OBSERVATION,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.CREATE_ACTION,
    PERMISSIONS.ASSIGN_ACTION,
    PERMISSIONS.UPDATE_ACTION,
    PERMISSIONS.VIEW_REPORTS,
  ],
  SAFETY_SUPERVISOR: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALL_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.MANAGE_TRAINING,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.CREATE_VISIT,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.CREATE_INSPECTION,
    PERMISSIONS.MANAGE_INSPECTION_TEMPLATES,
    PERMISSIONS.VIEW_OBSERVATIONS,
    PERMISSIONS.CREATE_OBSERVATION,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.CREATE_ACTION,
    PERMISSIONS.ASSIGN_ACTION,
    PERMISSIONS.UPDATE_ACTION,
    PERMISSIONS.VERIFY_ACTION,
    PERMISSIONS.CLOSE_ACTION,
    PERMISSIONS.REOPEN_ACTION,
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
  ],
  TRAINER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.MANAGE_TRAINING,
    PERMISSIONS.VIEW_REPORTS,
  ],
  RO_MANAGER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VIEW_OBSERVATIONS,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.UPDATE_ACTION,
    PERMISSIONS.VERIFY_ACTION,
    PERMISSIONS.CLOSE_ACTION,
    PERMISSIONS.VIEW_REPORTS,
  ],
  SUPERVISOR: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VIEW_OBSERVATIONS,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.UPDATE_ACTION,
    PERMISSIONS.VERIFY_ACTION,
    PERMISSIONS.CLOSE_ACTION,
    PERMISSIONS.VIEW_REPORTS,
  ],
  EMPLOYEE: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.UPDATE_ACTION,
  ],
  CUSTOMER_ATTENDANT: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.UPDATE_ACTION,
  ],
  CONTRACTOR: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_ACTIONS,
  ],
  DRIVER: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.UPDATE_ACTION,
  ],
  LPG_DELIVERY_PERSONNEL: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.UPDATE_ACTION,
  ],
  AUDITOR: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ALL_DASHBOARD,
    PERMISSIONS.VIEW_WORKFORCE,
    PERMISSIONS.VIEW_TRAINING,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VIEW_OBSERVATIONS,
    PERMISSIONS.VIEW_ACTIONS,
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],
};

export function hasPermission(role: RoleName, permission: Permission): boolean {
  const perms = ROLE_PERMISSIONS[role];
  return perms ? perms.includes(permission) : false;
}

export function hasAnyPermission(role: RoleName, permissions: Permission[]): boolean {
  return permissions.some((p) => hasPermission(role, p));
}

export function canVerifyActions(role: RoleName): boolean {
  return hasPermission(role, PERMISSIONS.VERIFY_ACTION);
}

export function canCloseActions(role: RoleName): boolean {
  return hasPermission(role, PERMISSIONS.CLOSE_ACTION);
}

export function isAdmin(role: RoleName): boolean {
  return role === 'SUPER_ADMIN' || role === 'CLIENT_ADMIN';
}

export function isFieldRole(role: RoleName): boolean {
  return ['FIELD_OFFICER', 'SAFETY_SUPERVISOR'].includes(role);
}

export function isManagementRole(role: RoleName): boolean {
  return [
    'SUPER_ADMIN',
    'CLIENT_ADMIN',
    'REGIONAL_MANAGER',
    'AREA_MANAGER',
  ].includes(role);
}

export const ROLE_DISPLAY_NAMES: Record<RoleName, string> = {
  SUPER_ADMIN: 'Super Admin',
  CLIENT_ADMIN: 'Client Admin',
  REGIONAL_MANAGER: 'Regional Manager',
  AREA_MANAGER: 'Area Manager',
  FIELD_OFFICER: 'Field Officer',
  SAFETY_SUPERVISOR: 'Safety Supervisor',
  TRAINER: 'Trainer',
  RO_MANAGER: 'RO Manager',
  SUPERVISOR: 'Supervisor',
  EMPLOYEE: 'Employee',
  CUSTOMER_ATTENDANT: 'Customer Attendant',
  CONTRACTOR: 'Contractor',
  DRIVER: 'Driver',
  LPG_DELIVERY_PERSONNEL: 'LPG Delivery Personnel',
  AUDITOR: 'Auditor',
};
