'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-form';
import { useMutation } from '@tanstack/react-query';
import { createClient } from '@/lib/supabase/client';
import { ArrowLeft, Save } from 'lucide-react';
import Link from 'next/link';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm as useReactHookForm } from 'react-hook-form';

const actionSchema = z.object({
  source_type: z.string().min(1, 'Source type is required'),
  issue_description: z.string().min(10, 'Issue description must be at least 10 characters'),
  detailed_description: z.string().optional(),
  location_id: z.string().min(1, 'Location is required'),
  responsible_id: z.string().min(1, 'Responsible person is required'),
  supervisor_id: z.string().min(1, 'Supervisor is required'),
  priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'CRITICAL']),
  due_date: z.string().min(1, 'Due date is required'),
});

type ActionFormValues = z.infer<typeof actionSchema>;

export default function NewActionPage() {
  const router = useRouter();
  const supabase = createClient();

  const { register, handleSubmit, formState: { errors, isSubmitting } } = useReactHookForm<ActionFormValues>({
    resolver: zodResolver(actionSchema),
    defaultValues: {
      source_type: 'MANUAL',
      priority: 'MEDIUM',
    }
  });

  const mutation = useMutation({
    mutationFn: async (values: ActionFormValues) => {
      const { data, error } = await supabase.from('corrective_actions').insert({
        ...values,
        status: 'OPEN',
        // action_number is auto-generated by DB trigger
      }).select().single();
      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      router.push(`/actions/${data.id}`);
    }
  });

  const onSubmit = (data: ActionFormValues) => {
    mutation.mutate(data);
  };

  return (
    <div className="p-4 md:p-6 max-w-4xl mx-auto">
      <div className="mb-6">
        <Link href="/actions" className="inline-flex items-center text-blue-600 hover:text-blue-800 mb-4 transition font-medium text-sm">
          <ArrowLeft size={16} className="mr-1" /> Back to Actions
        </Link>
        <h1 className="text-3xl font-bold text-slate-800">Create Corrective Action</h1>
        <p className="text-slate-500 mt-1">Report a safety issue or compliance violation.</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <form onSubmit={handleSubmit(onSubmit)} className="p-6 space-y-6">
          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-700">Source Type *</label>
              <select {...register('source_type')} className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
                <option value="MANUAL">Manual</option>
                <option value="INSPECTION">Safety Inspection</option>
                <option value="OBSERVATION">Observation</option>
                <option value="BEHAVIORAL">Behavioral Check</option>
              </select>
              {errors.source_type && <p className="text-red-500 text-xs">{errors.source_type.message}</p>}
            </div>
            
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-700">Priority *</label>
              <select {...register('priority')} className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none">
                <option value="LOW">Low</option>
                <option value="MEDIUM">Medium</option>
                <option value="HIGH">High</option>
                <option value="CRITICAL">Critical</option>
              </select>
              {errors.priority && <p className="text-red-500 text-xs">{errors.priority.message}</p>}
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700">Issue Description *</label>
            <input type="text" {...register('issue_description')} placeholder="Brief summary of the issue" className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none" />
            {errors.issue_description && <p className="text-red-500 text-xs">{errors.issue_description.message}</p>}
          </div>

          <div className="space-y-2">
            <label className="text-sm font-semibold text-slate-700">Detailed Description</label>
            <textarea {...register('detailed_description')} rows={4} placeholder="Full details of what needs to be fixed..." className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none"></textarea>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-700">Location ID *</label>
              <input type="text" {...register('location_id')} placeholder="e.g. LOC-1001" className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none" />
              {errors.location_id && <p className="text-red-500 text-xs">{errors.location_id.message}</p>}
            </div>
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-700">Due Date *</label>
              <input type="date" {...register('due_date')} className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none" />
              {errors.due_date && <p className="text-red-500 text-xs">{errors.due_date.message}</p>}
            </div>
          </div>

          <div className="grid md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-700">Responsible Person ID *</label>
              <input type="text" {...register('responsible_id')} placeholder="User ID" className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none" />
              {errors.responsible_id && <p className="text-red-500 text-xs">{errors.responsible_id.message}</p>}
            </div>
            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-700">Supervisor ID *</label>
              <input type="text" {...register('supervisor_id')} placeholder="Supervisor User ID" className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none" />
              {errors.supervisor_id && <p className="text-red-500 text-xs">{errors.supervisor_id.message}</p>}
            </div>
          </div>

          <div className="pt-4 border-t border-slate-200 flex justify-end gap-3">
            <Link href="/actions" className="px-5 py-2 border border-slate-300 text-slate-700 rounded-lg hover:bg-slate-50 transition">Cancel</Link>
            <button type="submit" disabled={isSubmitting || mutation.isPending} className="px-5 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition flex items-center gap-2 disabled:opacity-50">
              <Save size={18} /> {isSubmitting || mutation.isPending ? 'Saving...' : 'Create Action'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
